Add auth request event
cryostatio/cryostat pull request #522
Opened 2021-06-17 20:01 UTC by jan-law

Related #461 

Not tested yet.
How can I trigger the `OpenShiftAuthManager` to emit an event?

2021-06-17 20:15 UTC, andrewazores commented
> How can I trigger the OpenShiftAuthManager to emit an event?

You would need to build your Cryostat image and push it to a registry (ex. quay.io , under your own account/namespace). Then you can deploy your custom Cryostat image in CRC using the Operator. Once it's running in CRC it will automatically select the OpenShiftAuthManager, so set up a recording with the ALL metatemplate and after that most things you do will trigger the event to be recorded.

2021-06-25 14:49 UTC, andrewazores submitted a review, later dismissed
I've just built and deployed this to my crc instance and it looks great.

2021-06-25 14:52 UTC, andrewazores commented
[authrequest.tar.gz](https://github.com/cryostatio/cryostat/files/6716990/authrequest.tar.gz)

2021-06-25 14:57 UTC, jan-law commented
Glad it's working! I actually haven't been able to test this yet because my `crc start` still isn't working. Guillaume from the crc team has been helping me with the issue

2021-06-25 15:30 UTC, andrewazores commented on src/main/extras/app/Cryostat.xml
> + <event name="io.cyostat.net.OpenShiftAuthManager.AuthRequest">
typo: 'cyostat'

2021-06-25 15:31 UTC, andrewazores requested changes
The `web-client` submodule shouldn't be updated by this PR

2021-06-25 15:44 UTC, merged